// Generated by Naso -- WGSL compute backend
// kernel `dequantize_int8_symmetric`: 2 binding(s), one invocation per element, workgroup_size 64
// Loop order is source order; no vectorisation, tiling or schedule transformation is applied.

@group(0) @binding(0) var<storage, read> input: array<i32>;
@group(0) @binding(1) var<storage, read_write> output: array<f32>;

@group(0) @binding(2) var<uniform> scale_u: f32;

@compute @workgroup_size(64)
fn dequantize_int8_symmetric_compute(@builtin(global_invocation_id) global_id: vec3<u32>) {
    let i = i32(global_id.x);
    if (i >= 1024) { return; }
    let v = f32(input[i]);
    output[i] = (v * scale_u);
}
