// Generated by Naso -- WGSL compute backend
// kernel `relu_scale_f32`: 2 binding(s), one invocation per element, workgroup_size 64
// Loop order is source order; no vectorisation, tiling or schedule transformation is applied.

@group(0) @binding(0) var<storage, read> input: array<f32>;
@group(0) @binding(1) var<storage, read_write> output: array<f32>;

@group(0) @binding(2) var<uniform> scale_u: f32;

@compute @workgroup_size(64)
fn relu_scale_f32_compute(@builtin(global_invocation_id) global_id: vec3<u32>) {
    let i = i32(global_id.x);
    if (i >= 1024) { return; }
    let v = (input[i] * scale_u);
    output[i] = ((v + abs(v)) * 0.5);
}
