// Generated by Naso -- WGSL compute backend
// kernel `scale_clamp_f32`: 2 binding(s), one invocation per element, workgroup_size 64
// Loop order is source order; no vectorisation, tiling or schedule transformation is applied.

@group(0) @binding(0) var<storage, read> input: array<f32>;
@group(0) @binding(1) var<storage, read_write> output: array<f32>;

@group(0) @binding(2) var<uniform> scale_u: f32;
@group(0) @binding(3) var<uniform> lo_u: f32;
@group(0) @binding(4) var<uniform> hi_u: f32;

@compute @workgroup_size(64)
fn scale_clamp_f32_compute(@builtin(global_invocation_id) global_id: vec3<u32>) {
    let i = i32(global_id.x);
    if (i >= 1024) { return; }
    let v = (input[i] * scale_u);
    output[i] = clamp(v, lo_u, hi_u);
}
