#!/usr/bin/env node
/**
 * Compile every Naso kernel to WGSL with the native naso-compiler, and copy the
 * .naso sources into public/ so the browser can compile them too.
 *
 * Why both:
 *
 *   * These .wgsl + .abi.json artefacts are what CI checks. If the native
 *     compiler refuses a kernel, `npm run compile:kernels` fails here, before a
 *     browser is involved.
 *   * The .naso sources are copied to public/kernels/ because the running app
 *     compiles them ITSELF, in the browser, with the nasoc-wasm build. That is
 *     the property the demo exists to show: the WGSL on the GPU is generated by
 *     the verified compiler at page load, not committed next to it.
 *
 * The ABI is read from the compiler's stderr (it is a human-readable report
 * there; WGSL goes to stdout), so this script parses that report rather than
 * re-deriving buffer sizes by hand.
 *
 * Usage: node scripts/compile-kernels.js [--repo /path/to/naso]
 */

import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync, copyFileSync, existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const repoFlag = process.argv.indexOf('--repo');
const NASO_REPO = repoFlag >= 0 ? process.argv[repoFlag + 1] : process.env.NASO_REPO ?? '/home/node/naso';

const KERNELS = [
  { file: 'quantize_int8.naso', fn: 'quantize_int8_symmetric' },
  { file: 'quantize_int8.naso', fn: 'dequantize_int8_symmetric' },
  { file: 'quantize_int8.naso', fn: 'scale_clamp_f32' },
  { file: 'quantize_int8.naso', fn: 'silu_f32' },
  { file: 'quantize_int8.naso', fn: 'relu_scale_f32' },
];

const outDir = join(root, 'public', 'kernels');
mkdirSync(outDir, { recursive: true });

/** Parse the ABI report the compiler writes to stderr. */
function parseAbi(stderr, fn) {
  const lines = stderr.split('\n');
  const entryIdx = lines.findIndex(l => l.includes(`entry point \`${fn}`));
  if (entryIdx < 0) return null;

  const bindings = [];
  const scalars = [];
  let workgroupSize = 0;
  let dispatchGroups = 0;

  for (let i = entryIdx + 1; i < lines.length; i++) {
    const line = lines[i];
    const m = line.match(/^\s*binding\((\d+)\)\s+(\w+)\s*:\s+(\S+)\s+(\w+)\s+\((\d+) bytes(?:,\s*WGSL name\s+(\w+))?\)/);
    if (m) {
      const [, index, name, elem, kind, bytes, wgslName] = m;
      if (kind === 'uniform') {
        scalars.push({ name, type: elem, index: Number(index), wgslName: wgslName ?? `${name}_u`, bytes: Number(bytes) });
      } else {
        bindings.push({ name, elem, access: kind, index: Number(index), bytes: Number(bytes) });
      }
      continue;
    }
    const w = line.match(/workgroup_size (\d+) x, dispatch (\d+) workgroups/);
    if (w) {
      workgroupSize = Number(w[1]);
      dispatchGroups = Number(w[2]);
      break;
    }
    if (/^@group\(0\) entry point/.test(line)) continue;
  }

  return { entryPoint: `${fn}_compute`, workgroupSize, dispatchGroups, bindings, scalars };
}

/** Run the native compiler for one kernel, capturing stdout (WGSL) and stderr (ABI report). */
function runCapturing(fn, srcPath) {
  // spawnSync, not execFileSync: the ABI report goes to stderr and execFileSync
  // returns only stdout, so the report would be silently dropped on success.
  const res = spawnSync(
    'cargo',
    ['run', '--release', '-q', '-p', 'naso-compiler', '--', 'build', '--target', 'wgsl', '--kernel', fn, '--emit-abi', srcPath],
    { cwd: NASO_REPO, encoding: 'utf8', env: { ...process.env, CARGO_TERM_COLOR: 'never' }, maxBuffer: 64 * 1024 * 1024 },
  );
  const stdout = res.stdout ?? '';
  const stderr = (res.stderr ?? '') + (res.error ? String(res.error.message) : '');
  return { ok: res.status === 0, stdout, stderr };
}

if (!existsSync(NASO_REPO)) {
  console.error(`naso repo not found at ${NASO_REPO}; pass --repo <path> or set NASO_REPO`);
  process.exit(1);
}
console.log(`naso-compiler repo: ${NASO_REPO}`);

// 1. Copy the .naso sources the browser compiles.
const srcDir = join(root, 'kernels');
const files = readdirSync(srcDir).filter(f => f.endsWith('.naso'));
for (const f of files) {
  copyFileSync(join(srcDir, f), join(outDir, f));
  console.log(`copied kernels/${f} -> public/kernels/${f}`);
}

// 2. Compile each requested function natively and write its artefacts.
let failures = 0;
for (const { file, fn } of KERNELS) {
  const srcPath = join(srcDir, file);
  const { ok, stdout, stderr } = runCapturing(fn, srcPath);
  if (!ok) {
    console.error(`FAIL ${fn}: ${stderr.trim().split('\n').slice(0, 3).join(' | ')}`);
    failures++;
    continue;
  }
  const abi = parseAbi(stderr, fn);
  if (!abi) {
    console.error(`FAIL ${fn}: could not parse ABI from compiler output`);
    failures++;
    continue;
  }
  writeFileSync(join(outDir, `${fn}.wgsl`), stdout);
  writeFileSync(join(outDir, `${fn}.abi.json`), JSON.stringify(abi, null, 2));
  console.log(`compiled ${fn}: ${abi.bindings.length} storage + ${abi.scalars.length} scalar, ${abi.dispatchGroups} workgroups`);
}

if (failures > 0) {
  console.error(`${failures} kernel(s) failed to compile`);
  process.exit(1);
}
console.log(`ok: ${KERNELS.length} kernels -> public/kernels/`);
